#!/bin/sh
# Should be put into <repository>/.git/hooks/

perl "pre-commit.pl"

# if the execution of script returned error code, abort the commit
if [[ $? > 0 ]]
then
	echo "Commit aborted. You can use 'git commit --noverify' to skip this check."
	exit 1
fi
